site_name: Personal Docs
site_url: https://example.com/

repo_url: https://github.com/FrankyRay/Minecraft-Docs
repo_name: FrankyRay/Minecraft-Docs

nav:
  - Home: 
    - index.md
    - About: about.md
    - Test: test.md

theme: 
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/git-alt
  palette: 
  - scheme: default
    primary: deep purple
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate 
    primary: teal
    accent: yellow
    toggle:
      icon: material/weather-night
      name: Switch to light mode