site_name: Personal Docs
site_url: https://example.com/

repo_url: https://github.com/FrankyRay/Minecraft-Docs
repo_name: FrankyRay/Minecraft-Docs

nav:
  - Home: index.md
  - Commands:
    - Data Value: commands/data_value.md
    - T-Flip-Flop: commands/toggle.md
  - Misc:
    - about.md
    - Test: test.md

theme: 
  name: material
  features:
    - navigation.tabs
    - content.tabs.link
  icon:
    repo: fontawesome/brands/git-alt
  palette: 
  - scheme: default
    primary: deep purple
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate 
    primary: teal
    accent: yellow
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js